apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: rainbond
    meta.helm.sh/release-namespace: rbd-system
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    control-plane: rainbond-operator
    release: rainbond
  name: rainbond-operator
  namespace: rbd-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: rainbond-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: rainbond-operator
        release: rainbond
    spec:
      containers:
        - args:
            - --leader-elect
            - --zap-log-level=4
          command:
            - /manager
          env:
            - name: CHECK_PORT_OCCUPIED
              value: "true"
          image: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:v5.17.0-release
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: rainbond-operator
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var
              name: vardir
            - mountPath: /run
              name: rundir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rainbond-operator
      serviceAccountName: rainbond-operator
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /run
            type: Directory
          name: rundir
        - hostPath:
            path: /var
            type: Directory
          name: vardir