apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: rbd-http-routes
spec:
  http:
    - name: rbd-hub
      match:
        hosts:
          - goodrain.me
        paths:
          - /*
      backends:
        - serviceName: rbd-hub
          servicePort: 5000