apiVersion: v1
kind: Service
metadata:
  name: apisix-out
  namespace: itihey-system
spec:
  ports:
    - port: 9080
      protocol: TCP
      targetPort: 9080
      nodePort: 3000
  selector:
    name: gr7ba343
  type: NodePort

