apiVersion: v1
kind: Service
metadata:
  name: apisix-monitor
  namespace: ingress-apisix
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app.kubernetes.io/name: ingress-apisix-composite-deployment
  type: ClusterIP

---
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  namespace: rbd-system
  name: apisix-monitor
spec:
  plugins:
    - name: prometheus
      enable: true
      config:
        prefer_name: true


---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  namespace: rbd-system
  name: rbd-default-routes
spec:
  stream:
    - name: rbd-app-ui
      protocol: TCP
      match:
        ingressPort: 7070
      backend:
        serviceName: rbd-app-ui
        servicePort: 7070
    - name: rbd-api
      protocol: TCP
      match:
        ingressPort: 8443
      backend:
        serviceName: rbd-api-api
        servicePort: 8443
    - name: rbd-api-health
      protocol: TCP
      match:
        ingressPort: 8889
      backend:
        serviceName: rbd-api-healthz
        servicePort: 8889
    - name: rbd-api-websocket
      protocol: TCP
      match:
        ingressPort: 6060
      backend:
        serviceName: rbd-api-websocket
        servicePort: 6060
  http:
    - name: rbd-hub
      match:
        hosts:
          - goodrain.me
        paths:
          - /*
      backends:
        - serviceName: rbd-hub
          servicePort: 5000
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  namespace: rbd-system
  name: hub-image-repository
spec:
  hosts:
    - goodrain.me
  secret:
    name: hub-image-repository
    namespace: rbd-system

