apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: rbd-tcp-route
spec:
  stream:
    - name: rbd-api
      protocol: TCP
      match:
        ingressPort: 8443
      backend:
        serviceName: rbd-api-api
        servicePort: 8443

    - name: rbd-app-ui
      protocol: TCP
      match:
        ingressPort: 7070
      backend:
        serviceName:
        servicePort: 7070

    - name: rbd-api-healthz
      protocol: TCP
      match:
        ingressPort: 8889
      backend:
        serviceName: rbd-api-healthz
        servicePort: 8889

    - name: rbd-ws
      protocol: TCP
      match:
        ingressPort: 6060
      backend:
        serviceName: rbd-api-websocket
        servicePort: 6060

---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: db-route
spec:
  stream:
    - name: rbd-ws
      protocol: TCP
      match:
        ingressPort: 10000
      backend:
        serviceName: rbd-db-rw
        servicePort: 3306
    - name: rbd-monitor
      protocol: TCP
      match:
        ingressPort: 10001
      backend:
        serviceName: rbd-monitor
        servicePort: 9999