apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: tcp-route
spec:
  stream:
    - name: rbd-app-ui
      protocol: TCP
      match:
        ingressPort: 7070
      backend:
        serviceName: rbd-app-ui
        servicePort: 7070
